Project_Name: "Elecnet IP Tables"
Output_Dir: "./output/"
Asset_Dir: "./assets/"
Ping_Output: "./output/ping_output/"
PNS_Dir: "../../pns-elecnet/"
FW_Output: "./output/iptables_output/"
Wallpaper: "./assets/1140px-Australia_relief_map.jpg"
ACL_kernel_file: "./assets/elecnet_ACL.kgl"
policy_file: "./output/elecnet_policy.dot"
ip_map_file: "./output/ip_map.yaml"
topology_file: "./assets/elecnet_topology.pdf"
location_file: "./output/locations.yaml"
trig_file: "./output/elecnet.trig"
html_file: "./output/elecnet.html"
xml_file: "./output/elecnet_IP_Tables.xml"
ping_commands_file: "./output/ping_commands.yaml"
project_yaml_file: "./assets/elecnet_IP_Tables.yaml"
        
